// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { PartialUser } from './user';
import type { Snowflake } from './snowflake';

export type StatusType = 'idle' | 'dnd' | 'online' | 'offline';
export interface BasePresenceUpdate {
  user: PartialUser;
  status: StatusType;
  activities: Activity[];
  client_status: ClientStatus;
}

export interface PartialPresenceUpdate extends BasePresenceUpdate {
  guild_id?: Snowflake;
}

export interface ClientStatus {
  desktop: StatusType;
  mobile: StatusType;
  web: StatusType;
}

export interface ActivityTimestamps {
  start: number;
  end: number;
}

export interface ActivityParty {
  id: string;
  size: number[];
}

export interface ActivityAssets {
  large_image: string;
  large_text: string;
  small_image: string;
  small_text: string;
}

export interface ActivitySecrets {
  join: string;
  spectate: string;
  match: string;
}

export interface ActivityEmoji {
  name: string;
  id?: Snowflake;
  animated?: boolean;
}

export type ActivityType = 0 | 1 | 2 | 4 | 5;
export interface SendableActivity {
  name: string;
  type: ActivityType;
  url?: string | null;
}

export interface _BaseActivity extends SendableActivity {
  created_at: number;
}

export interface Activity extends _BaseActivity {
  state: string | null;
  details: string | null;
  timestamps: ActivityTimestamps;
  assets: ActivityAssets;
  party: ActivityParty;
  application_id: Snowflake;
  flags: number;
  emoji: ActivityEmoji | null;
  secrets: ActivitySecrets;
  session_id: string | null;
  instance: boolean;
  buttons: string[];
  sync_id: string;
}
