// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { User } from './user';
import type { Team } from './team';
import type { Snowflake } from './snowflake';

export interface BaseAppInfo {
  id: Snowflake;
  name: string;
  verify_key: string;
  icon: string | null;
  summary: string;
  description: string;
  cover_image: string | null;
  flags?: number;
  rpc_origins: string[];
}

export interface AppInfo extends BaseAppInfo {
  owner: User;
  bot_public?: boolean;
  bot_require_code_grant?: boolean;
  integration_public?: boolean;
  integration_require_code_grant?: boolean;
  team?: Team;
  guild_id?: Snowflake;
  primary_sku_id?: Snowflake;
  slug?: string;
  terms_of_service_url?: string;
  privacy_policy_url?: string;
  hook?: boolean;
  max_participants?: number;
  interactions_endpoint_url?: string;
  verification_state: number;
  store_application_state: number;
  rpc_application_state: number;
  interactions_endpoint_url: string;
}

export interface PartialAppInfo extends BaseAppInfo {
  hook: boolean;
  terms_of_service_url: string;
  privacy_policy_url: string;
  max_participants: number;
}
