// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { ApplicationCommand } from './command';
import type { PartialGuild } from './guild';
import type { Snowflake } from './snowflake';
import type { Team } from './team';
import type { APIUser, PartialUser } from './user';

export interface Token {
  token: string;
}

export interface OptionalToken {
  token: string | null;
}

export interface Secret {
  secret: string;
}

export interface _BaseApplication {
  id: Snowflake;
  name: string;
  description: string;
  icon: string | null;
  cover_image?: string;
  splash?: string;
  type: number | null;
  primary_sku_id?: Snowflake;
  summary?: '';
  deeplink_uri?: string;
  third_party_skus?: ThirdPartySKU[];
}

export interface BaseApplication extends _BaseApplication {
  bot?: PartialUser;
}

export interface IntegrationApplication extends BaseApplication {
  role_connections_verification_url?: string | null;
}

export interface PartialApplication extends _BaseApplication {
  owner?: APIUser;
  team?: Team;
  verify_key: string;
  flags?: number;
  rpc_origins?: string[];
  hook?: boolean;
  overlay?: boolean;
  overlay_warn?: boolean;
  overlay_compatibility_hook?: boolean;
  terms_of_service_url?: string;
  privacy_policy_url?: string;
  max_participants?: number | null;
  bot_public?: boolean;
  bot_require_code_grant?: boolean;
  integration_public?: boolean;
  integration_require_code_grant?: boolean;
  guild_id?: Snowflake;
  primary_sku_id?: Snowflake;
  slug?: string;
  developers?: Company[];
  publishers?: Company[];
  aliases?: string[];
  eula_id?: Snowflake;
  embedded_activity_config?: EmbeddedActivityConfig;
  guild?: PartialGuild;
  install_params?: ApplicationInstallParams;
  store_listing_sku_id?: Snowflake;
  executables?: ApplicationExecutable[];
}

export interface ApplicationDiscoverability {
  discoverability_state: number;
  discovery_eligibility_flags: number;
  bad_commands: ApplicationCommand[];
}

export type InteractionsVersion = 1 | 2;
export interface Application extends PartialApplication, IntegrationApplication {
  bot_disabled?: boolean;
  bot_quarantined?: boolean;
  redirect_uris: string[];
  interactions_endpoint_url: string | null;
  interactions_version: InteractionsVersion;
  interactions_event_types: string[];
  verification_state: number;
  store_application_state: number;
  rpc_application_state: number;
  creator_monetization_state: number;
  discoverability_state: number;
  discovery_eligibility_flags: number;
  monetization_state: number;
  monetization_eligibility_flags: number;
  approximate_guild_count?: number;
}

export interface WhitelistedUser {
  user: PartialUser;
  state: 1 | 2;
}

export interface Asset {
  id: Snowflake;
  name: string;
  type: number;
}

export interface StoreAsset {
  id: Snowflake;
  size: number;
  width: number;
  height: number;
  mime_type: string;
}

export interface Company {
  id: Snowflake;
  name: string;
}

export interface EULA {
  id: Snowflake;
  name: string;
  content: string;
}

export interface ApplicationExecutable {
  name: string;
  os: 'win32' | 'linux' | 'darwin';
  is_launcher: boolean;
}

export interface ThirdPartySKU {
  distributor: 'discord' | 'steam' | 'twitch' | 'uplay' | 'battlenet' | 'origin' | 'gog' | 'epic' | 'google_play';
  id: string | null;
  sku_id: string | null;
}

export interface BaseAchievement {
  id: Snowflake;
  name: string | Record<string, string | Record<string, string>>;
  name_localizations?: Record<string, string>;
  description: string | Record<string, string | Record<string, string>>;
  description_localizations?: Record<string, string>;
  icon_hash: string;
  secure: boolean;
  secret: boolean;
}

export interface Achievement extends BaseAchievement {
  application_id: Snowflake;
}

export interface Ticket {
  ticket: string;
}

export interface Branch {
  id: Snowflake;
  live_build_id?: Snowflake | null;
  created_at?: string;
  name?: string;
}

export interface BranchSize {
  size_kb: string;
}

export interface DownloadSignature {
  endpoint: string;
  expires: number;
  signature: string;
}

export interface Build {
  application_id?: Snowflake;
  created_at?: string;
  id: Snowflake;
  manifests: Manifest[];
  status: 'CORRUPTED' | 'INVALID' | 'READY' | 'VALIDATING' | 'UPLOADED' | 'UPLOADING' | 'CREATED';
  source_build_id?: Snowflake | null;
  version?: string | null;
}

export interface CreatedBuild {
  build: Build;
  manifest_uploads: Manifest[];
}

export interface BuildFile {
  id: Snowflake;
  md5_hash?: string;
}

export interface CreatedBuildFile {
  id: string;
  url: string;
}

export interface ManifestLabel {
  application_id: Snowflake;
  id: Snowflake;
  name?: string;
}

export interface Manifest {
  id: Snowflake;
  label: ManifestLabel;
  redistributable_label_ids?: Snowflake[];
  url: string | null;
}

export interface ActivityStatistics {
  application_id?: Snowflake;
  user_id?: Snowflake;
  total_duration: number;
  total_discord_sku_duration?: number;
  last_played_at: string;
}

export interface GlobalActivityStatistics {
  application_id: Snowflake;
  user_id: Snowflake;
  duration: number;
  updated_at: string;
}

export type EmbeddedActivityPlatform = 'web' | 'android' | 'ios';
export type EmbeddedActivityPlatformReleasePhase = 'in_development' | 'activities_team' | 'employee_release' | 'soft_launch' | 'global_launch';
export interface EmbeddedActivityPlatformConfig {
  label_type: 0 | 1 | 2;
  label_until: string | null;
  release_phase: EmbeddedActivityPlatformReleasePhase;
}

export interface EmbeddedActivityConfig {
  application_id?: Snowflake;
  activity_preview_video_asset_id?: Snowflake | null;
  client_platform_config: Record<EmbeddedActivityPlatform, EmbeddedActivityPlatformConfig>;
  default_orientation_lock_state: 1 | 2 | 3;
  tablet_default_orientation_lock_state: 1 | 2 | 3;
  free_period_ends_at?: string | null;
  free_period_starts_at?: string | null;
  premium_tier_requirement?: 1 | 2 | 3 | null;
  requires_age_gate: boolean;
  shelf_rank: number;
  supported_platforms: EmbeddedActivityPlatform[];
}

export interface ApplicationInstallParams {
  scopes: string[];
  permissions: number;
}

export interface ActiveDeveloperWebhook {
  channel_id: Snowflake;
  webhook_id: Snowflake;
}

export interface ActiveDeveloperResponse {
  follower: ActiveDeveloperWebhook;
}

export interface RoleConnectionMetadata {
  type: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
  key: string;
  name: string;
  description: string;
  name_localizations?: Record<string, string>;
  description_localizations?: Record<string, string>;
}

export interface PartialRoleConnection {
  platform_name: string | null;
  platform_username: string | null;
  metadata: Record<string, string>;
}

export interface RoleConnection extends PartialRoleConnection {
  application: BaseApplication;
  application_metadata: RoleConnectionMetadata[];
}

export interface UnverifiedApplication {
  name: string;
  hash: string;
  missing_data: string[];
}
