// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { Webhook } from './webhook';
import type { MFALevel, VerificationLevel, ExplicitContentFilterLevel, DefaultMessageNotificationLevel } from './guild';
import type { IntegrationExpireBehavior, PartialIntegration } from './integration';
import type { User } from './user';
import type { EntityType, EventStatus, GuildScheduledEvent } from './scheduled_event';
import type { Snowflake } from './snowflake';
import type { Role } from './role';
import type { ChannelType, DefaultReaction, PrivacyLevel, VideoQualityMode, PermissionOverwrite, ForumTag } from './channel';
import type { Thread } from './threads';

export type AuditLogEvent = 1 | 10 | 11 | 12 | 13 | 14 | 15 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 30 | 31 | 32 | 40 | 41 | 42 | 50 | 51 | 52 | 60 | 61 | 62 | 72 | 73 | 74 | 75 | 80 | 81 | 82 | 83 | 84 | 85 | 90 | 91 | 92 | 100 | 101 | 102 | 110 | 111 | 112 | 121 | 140 | 141 | 142 | 143 | 144 | 145 | 150 | 151;
export interface _AuditLogChange_Str {
  key:
    | 'name'
    | 'description'
    | 'preferred_locale'
    | 'vanity_url_code'
    | 'topic'
    | 'code'
    | 'allow'
    | 'deny'
    | 'permissions'
    | 'tags'
    | 'unicode_emoji';
  new_value: string;
  old_value: string;
}

export interface _AuditLogChange_AssetHash {
  key: 'icon_hash' | 'splash_hash' | 'discovery_splash_hash' | 'banner_hash' | 'avatar_hash' | 'asset';
  new_value: string;
  old_value: string;
}

export interface _AuditLogChange_Snowflake {
  key:
    | 'id'
    | 'owner_id'
    | 'afk_channel_id'
    | 'rules_channel_id'
    | 'public_updates_channel_id'
    | 'widget_channel_id'
    | 'system_channel_id'
    | 'application_id'
    | 'channel_id'
    | 'inviter_id'
    | 'guild_id';
  new_value: Snowflake;
  old_value: Snowflake;
}

export interface _AuditLogChange_Bool {
  key:
    | 'widget_enabled'
    | 'nsfw'
    | 'hoist'
    | 'mentionable'
    | 'temporary'
    | 'deaf'
    | 'mute'
    | 'nick'
    | 'enabled_emoticons'
    | 'region'
    | 'rtc_region'
    | 'available'
    | 'archived'
    | 'locked';
  new_value: boolean;
  old_value: boolean;
}

export interface _AuditLogChange_Int {
  key:
    | 'afk_timeout'
    | 'prune_delete_days'
    | 'position'
    | 'bitrate'
    | 'rate_limit_per_user'
    | 'color'
    | 'max_uses'
    | 'max_age'
    | 'user_limit'
    | 'auto_archive_duration'
    | 'default_auto_archive_duration'
    | 'default_thread_rate_limit_per_user'
    | 'communication_disabled_until'
    | 'flags';
  new_value: number;
  old_value: number;
}

export interface _AuditLogChange_ListRole {
  key: '$add' | '$remove';
  new_value: Role[];
  old_value: Role[];
}

export interface _AuditLogChange_MFALevel {
  key: 'mfa_level';
  new_value: MFALevel;
  old_value: MFALevel;
}

export interface _AuditLogChange_VerificationLevel {
  key: 'verification_level';
  new_value: VerificationLevel;
  old_value: VerificationLevel;
}

export interface _AuditLogChange_ExplicitContentFilter {
  key: 'explicit_content_filter';
  new_value: ExplicitContentFilterLevel;
  old_value: ExplicitContentFilterLevel;
}

export interface _AuditLogChange_DefaultMessageNotificationLevel {
  key: 'default_message_notifications';
  new_value: DefaultMessageNotificationLevel;
  old_value: DefaultMessageNotificationLevel;
}

export interface _AuditLogChange_ChannelType {
  key: 'type';
  new_value: ChannelType;
  old_value: ChannelType;
}

export interface _AuditLogChange_IntegrationExpireBehaviour {
  key: 'expire_behavior';
  new_value: IntegrationExpireBehavior;
  old_value: IntegrationExpireBehavior;
}

export interface _AuditLogChange_VideoQualityMode {
  key: 'video_quality_mode';
  new_value: VideoQualityMode;
  old_value: VideoQualityMode;
}

export interface _AuditLogChange_Overwrites {
  key: 'permission_overwrites';
  new_value: PermissionOverwrite[];
  old_value: PermissionOverwrite[];
}

export interface _AuditLogChange_PrivacyLevel {
  key: 'privacy_level';
  new_value: PrivacyLevel;
  old_value: PrivacyLevel;
}

export interface _AuditLogChange_Status {
  key: 'status';
  new_value: EventStatus;
  old_value: EventStatus;
}

export interface _AuditLogChange_EntityType {
  key: 'entity_type';
  new_value: EntityType;
  old_value: EntityType;
}

export interface _AuditLogChange_AppliedTags {
  key: 'applied_tags';
  new_value: Snowflake[];
  old_value: Snowflake[];
}

export interface _AuditLogChange_AvailableTags {
  key: 'available_tags';
  new_value: ForumTag[];
  old_value: ForumTag[];
}

export interface _AuditLogChange_DefaultReactionEmoji {
  key: 'default_reaction_emoji';
  new_value: DefaultReaction | null;
  old_value: DefaultReaction | null;
}

export interface AuditEntryInfo {
  delete_member_days: string;
  members_removed: string;
  channel_id: Snowflake;
  message_id: Snowflake;
  count: string;
  id: Snowflake;
  type: '0' | '1';
  role_name: string;
  application_id: Snowflake;
  guild_id: Snowflake;
  auto_moderation_rule_name: string;
  auto_moderation_rule_trigger_type: string;
}

export interface AuditLogEntry {
  target_id: string | null;
  user_id: Snowflake | null;
  id: Snowflake;
  action_type: AuditLogEvent;
  changes?: AuditLogChange[];
  options?: AuditEntryInfo;
  reason?: string;
}

export interface AuditLog {
  webhooks: Webhook[];
  users: User[];
  audit_log_entries: AuditLogEntry[];
  integrations: PartialIntegration[];
  threads: Thread[];
  guild_scheduled_events: GuildScheduledEvent[];
}
