// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { Snowflake } from './snowflake';

export type AutoModerationRuleTriggerType = 1 | 2 | 3 | 4;
export type AutoModerationActionTriggerType = 1 | 2 | 3;
export type AutoModerationRuleEventType = 1;
export type AutoModerationTriggerPresets = 1 | 2 | 3;
export interface Empty {
}

export interface _AutoModerationActionMetadataAlert {
  channel_id: Snowflake;
}

export interface _AutoModerationActionMetadataTimeout {
  duration_seconds: number;
}

export interface _AutoModerationActionMetadataCustomMessage {
  custom_message: string;
}

export interface _AutoModerationActionBlockMessage {
  type: 1;
  metadata?: _AutoModerationActionMetadataCustomMessage;
}

export interface _AutoModerationActionAlert {
  type: 2;
  metadata: _AutoModerationActionMetadataAlert;
}

export interface _AutoModerationActionTimeout {
  type: 3;
  metadata: _AutoModerationActionMetadataTimeout;
}

export type AutoModerationAction = _AutoModerationActionBlockMessage | _AutoModerationActionAlert | _AutoModerationActionTimeout;
export interface _AutoModerationTriggerMetadataKeyword {
  keyword_filter: string[];
  regex_patterns?: string[];
}

export interface _AutoModerationTriggerMetadataKeywordPreset {
  presets: AutoModerationTriggerPresets[];
  allow_list: string[];
}

export interface _AutoModerationTriggerMetadataMentionLimit {
  mention_total_limit: number;
}

export interface _BaseAutoModerationRule {
  id: Snowflake;
  guild_id: Snowflake;
  name: string;
  creator_id: Snowflake;
  event_type: AutoModerationRuleEventType;
  actions: AutoModerationAction[];
  enabled: boolean;
  exempt_roles: Snowflake[];
  exempt_channels: Snowflake[];
}

export interface _AutoModerationRuleKeyword extends _BaseAutoModerationRule {
  trigger_type: 1;
  trigger_metadata: _AutoModerationTriggerMetadataKeyword;
}

export interface _AutoModerationRuleKeywordPreset extends _BaseAutoModerationRule {
  trigger_type: 4;
  trigger_metadata: _AutoModerationTriggerMetadataKeywordPreset;
}

export interface _AutoModerationRuleOther extends _BaseAutoModerationRule {
  trigger_type: 2 | 3;
}

export type AutoModerationRule = _AutoModerationRuleKeyword | _AutoModerationRuleKeywordPreset | _AutoModerationRuleOther;
export interface AutoModerationActionExecution {
  guild_id: Snowflake;
  action: AutoModerationAction;
  rule_id: Snowflake;
  rule_trigger_type: AutoModerationRuleTriggerType;
  user_id: Snowflake;
  channel_id?: Snowflake;
  message_id?: Snowflake;
  alert_system_message_id?: Snowflake;
  content: string;
  matched_keyword: string | null;
  matched_content: string | null;
}
