// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

export interface BillingAddress {
  line_1: string;
  line_2?: string;
  name: string;
  postal_code?: string;
  city: string;
  state?: string;
  country: string;
  email?: string;
}

export interface BillingAddressToken {
  token: string;
}

export interface PartialPaymentSource {
  id: string;
  brand?: string;
  country?: string;
  last_4?: string;
  type: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16;
  payment_gateway: 1 | 2 | 3 | 4 | 5 | 6;
  invalid: boolean;
  flags: number;
  expires_month?: number;
  expires_year?: number;
  email?: string;
  bank?: string;
  username?: string;
  screen_status: number;
}

export interface PaymentSource extends PartialPaymentSource {
  billing_address: BillingAddress;
  default: boolean;
}

export interface PremiumUsageValue {
  value: number;
}

export interface PremiumUsage {
  nitro_sticker_sends: PremiumUsageValue;
  total_animated_emojis: PremiumUsageValue;
  total_global_emojis: PremiumUsageValue;
  total_large_uploads: PremiumUsageValue;
  total_hd_streams: PremiumUsageValue;
  hd_hours_streamed: PremiumUsageValue;
}
