// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { PartialUser } from './user';
import type { Snowflake } from './snowflake';
import type { MemberWithUser } from './guild';
import type { ThreadMetadata, ThreadMember, ThreadArchiveDuration, ThreadType } from './threads';

export type OverwriteType = 0 | 1;
export interface PermissionOverwrite {
  id: Snowflake;
  type: OverwriteType;
  allow: string;
  deny: string;
}

export type ChannelTypeWithoutThread = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 13 | 14 | 15;
export type ChannelType = ChannelTypeWithoutThread | ThreadType;
export interface _BaseChannel {
  id: Snowflake;
}

export interface _BaseGuildChannel extends _BaseChannel {
  guild_id: Snowflake;
  position: number;
  permission_overwrites: PermissionOverwrite[];
  parent_id: Snowflake | null;
  name: string;
  flags: number;
}

export interface PartialRecipient {
  username: string;
}

export interface PartialChannel extends _BaseChannel {
  name: string | null;
  type: ChannelType;
  icon?: string | null;
  recipients?: PartialRecipient[];
}

export interface _BaseTextChannel extends _BaseGuildChannel {
  topic: string;
  last_message_id: Snowflake | null;
  last_pin_timestamp: string;
  rate_limit_per_user: number;
  default_thread_rate_limit_per_user: number;
  default_auto_archive_duration: ThreadArchiveDuration;
  nsfw: boolean;
}

export interface TextChannel extends _BaseTextChannel {
  type: 0;
}

export interface NewsChannel extends _BaseTextChannel {
  type: 5;
}

export type VideoQualityMode = 1 | 2;
export interface VoiceChannel extends _BaseTextChannel {
  type: 2;
  bitrate: number;
  user_limit: number;
  rtc_region?: string | null;
  video_quality_mode?: VideoQualityMode;
}

export interface CategoryChannel extends _BaseGuildChannel {
  type: 4;
}

export interface StageChannel extends _BaseGuildChannel {
  type: 13;
  bitrate: number;
  user_limit: number;
  rtc_region?: string | null;
  topic?: string;
  nsfw: boolean;
}

export interface DirectoryChannel extends _BaseGuildChannel {
  type: 14;
  last_message_id: Snowflake | null;
  topic: string | null;
}

export interface ThreadChannel extends _BaseChannel {
  type: 10 | 11 | 12;
  guild_id: Snowflake;
  parent_id: Snowflake;
  owner_id: Snowflake;
  nsfw: boolean;
  last_message_id: Snowflake | null;
  rate_limit_per_user: number;
  message_count: number;
  member_count: number;
  thread_metadata: ThreadMetadata;
  member?: ThreadMember;
  owner_id?: Snowflake;
  rate_limit_per_user?: number;
  last_message_id?: Snowflake | null;
  last_pin_timestamp?: string;
  applied_tags?: Snowflake[];
  flags: number;
}

export interface DefaultReaction {
  emoji_id: Snowflake | null;
  emoji_name: string | null;
}

export interface ForumTag {
  id: Snowflake;
  name: string;
  moderated: boolean;
  emoji_id: Snowflake | null;
  emoji_name: string | null;
}

export type ForumOrderType = 0 | 1;
export type ForumLayoutType = 0 | 1 | 2;
export interface ForumChannel extends _BaseTextChannel {
  type: 15;
  available_tags: ForumTag[];
  default_reaction_emoji: DefaultReaction | null;
  default_sort_order: ForumOrderType | null;
  default_forum_layout?: ForumLayoutType;
}

export interface DMChannel extends _BaseChannel {
  type: 1;
  last_message_id: Snowflake | null;
  recipients: PartialUser[];
  is_message_request?: boolean;
  is_message_request_timestamp?: string;
  is_spam?: boolean;
}

export interface GroupDMChannel extends _BaseChannel {
  type: 3;
  name: string | null;
  icon: string | null;
  owner_id: Snowflake;
  recipients: PartialUser[];
}

export type Channel = GuildChannel | DMChannel | GroupDMChannel;
export type PrivacyLevel = 1 | 2;
export interface StageInstance {
  id: Snowflake;
  guild_id: Snowflake;
  channel_id: Snowflake;
  topic: string;
  privacy_level: PrivacyLevel;
  discoverable_disabled: boolean;
  invite_code: string | null;
  guild_scheduled_event_id: number | null;
}

export interface InviteStageInstance {
  members: MemberWithUser[];
  participant_count: number;
  speaker_count: number;
  topic: string;
}

export interface CallEligibility {
  ringable: boolean;
}
