// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { IntegrationApplication } from './application';
import type { ChannelType } from './channel';
import type { Snowflake } from './snowflake';

export type ApplicationCommandType = 1 | 2 | 3;
export type ApplicationCommandOptionType = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11;
export interface _BaseApplicationCommandOption {
  name: string;
  description: string;
}

export interface _SubCommandCommandOption extends _BaseApplicationCommandOption {
  type: 1;
  options: _ValueApplicationCommandOption[];
}

export interface _SubCommandGroupCommandOption extends _BaseApplicationCommandOption {
  type: 2;
  options: _SubCommandCommandOption[];
}

export interface _BaseValueApplicationCommandOption extends _BaseApplicationCommandOption {
  required: boolean;
}

export interface _StringApplicationCommandOptionChoice {
  name: string;
  value: string;
}

export interface _StringApplicationCommandOption extends _BaseApplicationCommandOption {
  type: 3;
  choices?: _StringApplicationCommandOptionChoice[];
  autocomplete?: boolean;
}

export interface _IntegerApplicationCommandOptionChoice {
  name: string;
  value: number;
}

export interface _IntegerApplicationCommandOption extends _BaseApplicationCommandOption {
  type: 4;
  min_value: number;
  max_value: number;
  choices: _IntegerApplicationCommandOptionChoice[];
  autocomplete: boolean;
}

export interface _BooleanApplicationCommandOption extends _BaseValueApplicationCommandOption {
  type: 5;
}

export interface _ChannelApplicationCommandOptionChoice extends _BaseApplicationCommandOption {
  type: 7;
  channel_types?: ChannelType[];
}

export interface _NonChannelSnowflakeApplicationCommandOptionChoice extends _BaseValueApplicationCommandOption {
  type: 6 | 8 | 9 | 11;
}

export interface _NumberApplicationCommandOptionChoice {
  name: string;
  value: number;
}

export interface _NumberApplicationCommandOption extends _BaseValueApplicationCommandOption {
  type: 10;
  min_value: number;
  max_value: number;
  choices: _NumberApplicationCommandOptionChoice[];
  autocomplete: boolean;
}

export type SubCommand = _SubCommandCommandOption | _SubCommandGroupCommandOption;
export interface _BaseApplicationCommand {
  id: Snowflake;
  application_id: Snowflake;
  name: string;
  version: Snowflake;
}

export interface _ChatInputApplicationCommand extends _BaseApplicationCommand {
  description: string;
  type: 1;
  options?: ApplicationCommandOption[];
}

export interface _BaseContextMenuApplicationCommand extends _BaseApplicationCommand {
  description: "";
}

export interface _UserApplicationCommand extends _BaseContextMenuApplicationCommand {
  type: 2;
}

export interface _MessageApplicationCommand extends _BaseContextMenuApplicationCommand {
  type: 3;
}

export interface _GuildChatInputApplicationCommand extends _ChatInputApplicationCommand {
  guild_id: Snowflake;
}

export interface _GuildUserApplicationCommand extends _UserApplicationCommand {
  guild_id: Snowflake;
}

export interface _GuildMessageApplicationCommand extends _MessageApplicationCommand {
  guild_id: Snowflake;
}

export type ApplicationCommandPermissionType = 1 | 2;
export interface ApplicationCommandPermissions {
  id: Snowflake;
  type: ApplicationCommandPermissionType;
  permission: boolean;
}

export interface GuildApplicationCommandPermissions {
  id: Snowflake;
  application_id: Snowflake;
  guild_id: Snowflake;
  permissions: ApplicationCommandPermissions[];
}

export interface ApplicationCommandCursor {
  next: string | null;
  previous: string | null;
  repaired: string | null;
}

export interface ApplicationCommandIndex {
  application_commands: ApplicationCommand[];
  applications: IntegrationApplication[] | null;
}

export interface GuildApplicationCommandIndex extends ApplicationCommandIndex {
  version: Snowflake;
}

export interface ApplicationCommandSearch extends ApplicationCommandIndex {
  cursor: ApplicationCommandCursor;
}
