// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { PartialEmoji } from './emoji';

export type ComponentType = 1 | 2 | 3 | 4;
export type ButtonStyle = 1 | 2 | 3 | 4 | 5;
export type TextStyle = 1 | 2;
export interface MessageActionRow {
  type: 1;
  components: MessageChildComponent[];
}

export interface ModalActionRow {
  type: 1;
  components: ModalChildComponent[];
}

export type ActionRow = MessageActionRow | ModalActionRow;
export interface ButtonComponent {
  type: 2;
  style: ButtonStyle;
  custom_id?: string;
  url?: string;
  disabled?: boolean;
  emoji?: PartialEmoji;
  label?: string;
}

export interface SelectOption {
  label: string;
  value: string;
  default: boolean;
  description?: string;
  emoji?: PartialEmoji;
}

export interface SelectMenu {
  type: 3;
  custom_id: string;
  options: SelectOption[];
  placeholder?: string;
  min_values?: number;
  max_values?: number;
  disabled?: boolean;
}

export interface TextInput {
  type: 4;
  custom_id: string;
  style: TextStyle;
  label: string;
  placeholder?: string;
  value?: string;
  required?: boolean;
  min_length?: number;
  max_length?: number;
}

export type MessageChildComponent = ButtonComponent | SelectMenu;
export type ModalChildComponent = TextInput;
export type ActionRowChildComponent = MessageChildComponent | ModalChildComponent;
export type Component = ActionRow | ActionRowChildComponent;
