// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { PartialGuild, _GuildCounts } from './guild';
import type { ExternalScheduledEvent, StageInstanceScheduledEvent, VoiceScheduledEvent } from './scheduled_event';
import type { Snowflake } from './snowflake';

export interface _DirectoryScheduledEvent {
  guild: PartialGuild;
  user_rsvp: boolean;
  user_count: number;
}

export interface _DirectoryStageInstanceScheduledEvent extends _DirectoryScheduledEvent, StageInstanceScheduledEvent {
}

export interface _DirectoryVoiceScheduledEvent extends _DirectoryScheduledEvent, VoiceScheduledEvent {
}

export interface _DirectoryExternalScheduledEvent extends _DirectoryScheduledEvent, ExternalScheduledEvent {
}

export interface DirectoryGuild extends PartialGuild, _GuildCounts {
  featurable_in_directory: boolean;
}

export type DirectoryEntryType = 0 | 1;
export type DirectoryCategory = 0 | 1 | 2 | 3 | 5;
export type DirectoryCounts = Record<DirectoryCategory, number>;
export interface PartialDirectoryEntry {
  type: DirectoryEntryType;
  primary_category_id?: DirectoryCategory;
  directory_channel_id: Snowflake;
  author_id: Snowflake;
  entity_id: Snowflake;
  created_at: string;
  description: string | null;
}

export interface DirectoryEntry extends PartialDirectoryEntry {
  guild?: DirectoryGuild;
  guild_scheduled_event?: DirectoryScheduledEvent;
}

export interface DirectoryBroadcast {
  can_broadcast: boolean;
}
