// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

export interface EmbedFooter {
  text: string;
  icon_url?: string;
  proxy_icon_url?: string;
}

export interface EmbedField {
  name: string;
  value: string;
  inline?: boolean;
}

export interface EmbedThumbnail {
  url: string;
  proxy_url: string;
  height: number;
  width: number;
}

export interface EmbedVideo {
  url: string;
  proxy_url: string;
  height: number;
  width: number;
}

export interface EmbedImage {
  url: string;
  proxy_url: string;
  height: number;
  width: number;
}

export interface EmbedProvider {
  name: string;
  url: string;
}

export interface EmbedAuthor {
  name: string;
  url: string;
  icon_url: string;
  proxy_icon_url: string;
}

export type EmbedType = 'rich' | 'image' | 'video' | 'gifv' | 'article' | 'link' | 'auto_moderation_message';
export interface Embed {
  title: string;
  type: EmbedType;
  description: string;
  url: string;
  timestamp: string;
  color: number;
  footer: EmbedFooter;
  image: EmbedImage;
  thumbnail: EmbedThumbnail;
  video: EmbedVideo;
  provider: EmbedProvider;
  author: EmbedAuthor;
  fields: EmbedField[];
}
