// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { Snowflake, SnowflakeList } from './snowflake';
import type { User } from './user';

export interface PartialEmoji {
  id: Snowflake | null;
  name: string | null;
}

export interface Emoji extends PartialEmoji {
  roles: SnowflakeList;
  user: User;
  require_colons: boolean;
  managed: boolean;
  animated: boolean;
  available: boolean;
}

export interface EditEmoji {
  name: string;
  roles: SnowflakeList | null;
}

export interface TopEmoji {
  emoji_id: Snowflake;
  emoji_rank: number;
}

export interface TopEmojis {
  items: TopEmoji[];
}
