// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { PartialPayment } from './payments';
import type { Promotion } from './promotions';
import type { Snowflake } from './snowflake';
import type { PublicSKU, PublicStoreListing } from './store';
import type { PartialSubscriptionPlan, SubscriptionPlan, SubscriptionTrial } from './subscriptions';
import type { PartialUser } from './user';

export interface Entitlement {
  id: Snowflake;
  type: 1 | 2 | 3 | 4 | 5 | 6 | 7;
  user_id: Snowflake;
  sku_id: Snowflake;
  application_id: Snowflake;
  promotion_id: Snowflake | null;
  parent_id?: Snowflake;
  guild_id?: Snowflake;
  branches?: Snowflake[];
  gifter_user_id?: Snowflake;
  gift_style?: 1 | 2 | 3;
  gift_batch_id?: Snowflake;
  gift_code_flags?: number;
  deleted: boolean;
  consumed?: boolean;
  starts_at?: string;
  ends_at?: string;
  subscription_id?: Snowflake;
  subscription_plan?: PartialSubscriptionPlan;
  sku?: PublicSKU;
  payment?: PartialPayment;
}

export interface GatewayGift {
  code: string;
  uses: number;
  sku_id: Snowflake;
  channel_id?: Snowflake;
  guild_id?: Snowflake;
}

export interface Gift extends GatewayGift {
  expires_at: string | null;
  application_id: Snowflake;
  batch_id?: Snowflake;
  entitlement_branches?: Snowflake[];
  gift_style?: 1 | 2 | 3 | null;
  flags: number;
  max_uses: number;
  uses: number;
  redeemed: boolean;
  revoked?: boolean;
  store_listing?: PublicStoreListing;
  promotion?: Promotion;
  subscription_trial?: SubscriptionTrial;
  subscription_plan?: SubscriptionPlan;
  user?: PartialUser;
}

export interface GiftBatch {
  id: Snowflake;
  sku_id: Snowflake;
  amount: number;
  description?: string;
  entitlement_branches?: Snowflake[];
  entitlement_starts_at?: string;
  entitlement_ends_at?: string;
}
