// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

export interface FormError {
  code: string;
  message: string;
}

export interface FormErrorWrapper {
  _errors: FormError[];
}

export type FormErrors = FormErrorWrapper | Record<string, 'FormErrors'>;
export interface Error {
  code: number;
  message: string;
  errors?: FormErrors;
}

export type CaptchaService = 'hcaptcha' | 'recaptcha';
export interface CaptchaRequired {
  captcha_key: string[];
  captcha_service: CaptchaService;
  captcha_sitekey: string | null;
  captcha_rqdata?: string;
  captcha_rqtoken?: string;
}
