// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { Activity, BasePresenceUpdate, PartialPresenceUpdate, StatusType } from './activity';
import type { BaseAchievement } from './application';
import type { AuditLogEntry } from './audit_log';
import type { AutoModerationAction, AutoModerationRuleTriggerType } from './automod';
import type { ChannelType, DMChannel, GroupDMChannel, StageInstance } from './channel';
import type { Emoji, PartialEmoji } from './emoji';
import type { Entitlement, GatewayGift } from './entitlements';
import type { GuildExperiment, UserExperiment } from './experiment';
import type { ApplicationCommandCounts, Guild, SupplementalGuild, UnavailableGuild } from './guild';
import type { BaseIntegration, IntegrationApplication } from './integration';
import type { Modal } from './interactions';
import type { _InviteTargetType } from './invite';
import type { LibraryApplication } from './library';
import type { MemberWithPresence, MemberWithUser } from './member';
import type { Message } from './message';
import type { Payment } from './payments';
import type { ReadState, ReadStateType } from './read_state';
import type { Role } from './role';
import type { GuildScheduledEvent } from './scheduled_event';
import type { Snowflake } from './snowflake';
import type { GuildSticker } from './sticker';
import type { PremiumGuildSubscriptionSlot } from './subscriptions';
import type { BaseThreadMember, Thread, ThreadMember } from './threads';
import type {
  Connection,
  FriendSuggestion,
  PartialConsentSettings,
  PartialUser,
  ProtoSettingsType,
  Relationship,
  RelationshipType,
  User,
  UserGuildSettings,
} from './user';
import type { GuildVoiceState, PrivateVoiceState, VoiceState } from './voice';

export interface UserPresenceUpdateEvent extends BasePresenceUpdate {
}

export type PresenceUpdateEvent = PartialPresenceUpdate | UserPresenceUpdateEvent;
export interface Gateway {
  url: string;
}

export interface ShardInfo {
  shard_id: number;
  shard_count: number;
}

export interface ResumedEvent {
  _trace: string[];
}

export interface ReadyEvent extends ResumedEvent {
  _trace: string[];
  api_code_version: number;
  analytics_token: string;
  auth_session_id_hash: string;
  auth_token?: string;
  connected_accounts: Connection[];
  consents: PartialConsentSettings;
  country_code: string;
  experiments: UserExperiment[];
  friend_suggestion_count: number;
  geo_ordered_rtc_regions: string[];
  guild_experiments: GuildExperiment[];
  guilds: Guild[];
  merged_members: MemberWithUser[][];
  pending_payments?: Payment[];
  private_channels: (DMChannel | GroupDMChannel)[];
  read_state: Versioned<ReadState>;
  relationships: Relationship[];
  resume_gateway_url: string;
  required_action?: string;
  sessions: Session[];
  session_id: string;
  session_type: 'normal';
  shard?: ShardInfo;
  tutorial: Tutorial | null;
  user: User;
  user_guild_settings: Versioned<UserGuildSettings>;
  user_settings_proto?: string;
  users: PartialUser[];
  v: number;
}

export interface ClientInfo {
  version: number;
  os: string;
  client: string;
}

export interface Session {
  session_id: string;
  active?: boolean;
  client_info: ClientInfo;
  status: StatusType;
  activities: Activity[];
}

export interface MergedPresences {
  friends: UserPresenceUpdateEvent[];
  guilds: PartialPresenceUpdate[][];
}

export interface ReadySupplementalEvent {
  guilds: SupplementalGuild[];
  merged_members: MemberWithUser[][];
  merged_presences: MergedPresences;
  lazy_private_channels: (DMChannel | GroupDMChannel)[];
  disclose: string[];
}

export interface Versioned<T> {
  entries: T[];
  version: number;
  partial: boolean;
}

export interface Tutorial {
  indicators_suppressed: boolean;
  indicators_confirmed: string[];
}

export type NoEvent = null;
export type MessageCreateEvent = Message;
export type SessionsReplaceEvent = Session[];
export interface MessageDeleteEvent {
  id: Snowflake;
  channel_id: Snowflake;
  guild_id?: Snowflake;
}

export interface MessageDeleteBulkEvent {
  ids: Snowflake[];
  channel_id: Snowflake;
  guild_id?: Snowflake;
}

export interface MessageUpdateEvent extends Message {
  channel_id: Snowflake;
}

export interface MessageReactionAddEvent {
  user_id: Snowflake;
  channel_id: Snowflake;
  message_id: Snowflake;
  emoji: PartialEmoji;
  member?: MemberWithUser;
  guild_id?: Snowflake;
  message_author_id?: Snowflake;
}

export interface MessageReactionRemoveEvent {
  user_id: Snowflake;
  channel_id: Snowflake;
  message_id: Snowflake;
  emoji: PartialEmoji;
  guild_id?: Snowflake;
}

export interface MessageReactionRemoveAllEvent {
  message_id: Snowflake;
  channel_id: Snowflake;
  guild_id?: Snowflake;
}

export interface MessageReactionRemoveEmojiEvent {
  emoji: PartialEmoji;
  message_id: Snowflake;
  channel_id: Snowflake;
  guild_id?: Snowflake;
}

export type UserUpdateEvent = User;
export interface InviteCreateEvent extends _InviteTargetType {
  code: string;
  type: 0;
  channel_id: Snowflake;
  guild_id: Snowflake;
  inviter?: PartialUser;
  expires_at: string | null;
  created_at: string;
  uses: number;
  max_age: number;
  max_uses: number;
  temporary: boolean;
  flags?: number;
}

export interface InviteDeleteEvent {
  code: string;
  channel_id: Snowflake;
  guild_id: Snowflake;
}

export interface _ChannelEvent {
  id: Snowflake;
  type: ChannelType;
}

export interface ChannelRecipientEvent {
  channel_id: Snowflake;
  user: PartialUser;
}

export interface ChannelPinsUpdateEvent {
  channel_id: Snowflake;
  guild_id?: Snowflake;
  last_pin_timestamp?: string | null;
}

export interface ChannelPinsAckEvent {
  channel_id: Snowflake;
  timestamp: string;
  version: number;
}

export interface MessageAckEvent {
  channel_id: Snowflake;
  message_id: Snowflake;
  flags: number | null;
  last_viewed: number | null;
  manual?: boolean;
  mention_count?: number;
  ack_type?: ReadStateType;
  version: number;
}

export interface NonChannelAckEvent {
  entity_id: Snowflake;
  resource_id: Snowflake;
  ack_type: number;
  version: number;
}

export interface ThreadCreateEvent extends Thread {
  newly_created: boolean;
  members: ThreadMember[];
}

export type ThreadUpdateEvent = Thread;
export interface ThreadDeleteEvent {
  id: Snowflake;
  guild_id: Snowflake;
  parent_id: Snowflake;
  type: ChannelType;
}

export interface ThreadListSyncEvent {
  guild_id: Snowflake;
  threads: Thread[];
  members: ThreadMember[];
  channel_ids?: Snowflake[];
  most_recent_messages: Message[];
}

export interface ThreadMemberUpdate extends ThreadMember {
  guild_id: Snowflake;
}

export interface ThreadMembersUpdate {
  id: Snowflake;
  guild_id: Snowflake;
  member_count: number;
  added_members?: ThreadMember[];
  removed_member_ids?: Snowflake[];
}

export interface ThreadMemberListUpdateEvent {
  guild_id: Snowflake;
  thread_id: Snowflake;
  members: BaseThreadMember[];
}

export interface GuildMemberAddEvent extends MemberWithUser {
  guild_id: Snowflake;
  presence?: BasePresenceUpdate;
}

export interface SnowflakeUser {
  id: Snowflake;
}

export interface GuildMemberRemoveEvent {
  guild_id: Snowflake;
  user: PartialUser | SnowflakeUser;
}

export interface GuildMemberUpdateEvent {
  guild_id: Snowflake;
  roles: Snowflake[];
  user: PartialUser;
  avatar: string | null;
  joined_at: string | null;
  flags: number;
  nick?: string;
  premium_since?: string | null;
  deaf?: boolean;
  mute?: boolean;
  pending?: boolean;
  communication_disabled_until?: string;
}

export interface GuildEmojisUpdateEvent {
  guild_id: Snowflake;
  emojis: Emoji[];
}

export interface GuildStickersUpdateEvent {
  guild_id: Snowflake;
  stickers: GuildSticker[];
}

export type GuildDeleteEvent = UnavailableGuild;
export interface _GuildBanEvent {
  guild_id: Snowflake;
  user: PartialUser;
}

export interface _GuildRoleEvent {
  guild_id: Snowflake;
  role: Role;
}

export interface GuildRoleDeleteEvent {
  guild_id: Snowflake;
  role_id: Snowflake;
}

export interface GuildMembersChunkEvent {
  guild_id: Snowflake;
  members: MemberWithUser[];
  chunk_index: number;
  chunk_count: number;
  not_found?: Snowflake[];
  presences?: PartialPresenceUpdate[];
  nonce?: string;
}

export interface GuildIntegrationsUpdateEvent {
  guild_id: Snowflake;
}

export interface _IntegrationEvent extends BaseIntegration {
  guild_id: Snowflake;
  role_id: Snowflake | null;
  enable_emoticons: boolean;
  subscriber_count: number;
  revoked: boolean;
  application: IntegrationApplication;
}

export interface IntegrationDeleteEvent {
  id: Snowflake;
  guild_id: Snowflake;
  application_id?: Snowflake;
}

export interface WebhooksUpdateEvent {
  guild_id: Snowflake;
  channel_id: Snowflake;
}

export interface _GuildScheduledEventUsersEvent {
  guild_scheduled_event_id: Snowflake;
  user_id: Snowflake;
  guild_id: Snowflake;
}

export type VoiceStateUpdateEvent = GuildVoiceState | PrivateVoiceState;
export interface VoiceServerUpdateEvent {
  token: string;
  guild_id: Snowflake;
  channel_id: Snowflake;
  endpoint: string | null;
}

export interface TypingStartEvent {
  channel_id: Snowflake;
  user_id: Snowflake;
  timestamp: number;
  guild_id?: Snowflake;
  member?: MemberWithUser;
}

export type ConnectionEvent = Connection;
export interface PartialConnectionEvent {
  user_id: Snowflake;
}

export interface ConnectionsLinkCallbackEvent {
  provider: string;
  callback_code: string;
  callback_state: string;
}

export interface OAuth2TokenRevokeEvent {
  access_token: string;
}

export interface AuthSessionChangeEvent {
  auth_session_id_hash: string;
}

export interface PaymentClientAddEvent {
  purchase_token_hash: string;
  expires_at: string;
}

export interface AchievementUpdatePayload {
  application_id: Snowflake;
  achievement: BaseAchievement;
  percent_complete: number;
}

export type PremiumGuildSubscriptionSlotEvent = PremiumGuildSubscriptionSlot;
export interface RequiredActionEvent {
  required_action: string;
}

export interface BillingPopupBridgeCallbackEvent {
  payment_source_type: number;
  state: string;
  path: string;
  query: string;
}

export type PaymentUpdateEvent = Payment;
export type EntitlementEvent = Entitlement;
export type LibraryApplicationUpdateEvent = LibraryApplication;
export interface RelationshipAddEvent extends Relationship {
  should_notify?: boolean;
}

export interface RelationshipEvent {
  id: Snowflake;
  type: RelationshipType;
  nickname: string | null;
}

export type FriendSuggestionCreateEvent = FriendSuggestion;
export interface FriendSuggestionDeleteEvent {
  suggested_user_id: Snowflake;
}

export interface ProtoSettings {
  proto: string;
  type: ProtoSettingsType;
}

export interface ProtoSettingsEvent {
  settings: ProtoSettings;
  partial: boolean;
}

export interface RecentMentionDeleteEvent {
  message_id: Snowflake;
}

export interface AutoModerationActionExecution {
  guild_id: Snowflake;
  action: AutoModerationAction;
  rule_id: Snowflake;
  rule_trigger_type: AutoModerationRuleTriggerType;
  user_id: Snowflake;
  channel_id?: Snowflake;
  message_id?: Snowflake;
  alert_system_message_id?: Snowflake;
  content: string;
  matched_keyword: string | null;
  matched_content: string | null;
}

export interface GuildAuditLogEntryCreate extends AuditLogEntry {
  guild_id: Snowflake;
}

export interface PartialUpdateChannel {
  id: Snowflake;
  last_message_id: Snowflake | null;
  last_pin_timestamp?: string | null;
}

export interface PassiveUpdateEvent {
  guild_id: Snowflake;
  channels: PartialUpdateChannel[];
  voice_states?: VoiceState[];
  members?: MemberWithUser[];
}

export interface GuildApplicationCommandIndexUpdateEvent {
  guild_id: Snowflake;
}

export interface UserNoteUpdateEvent {
  id: Snowflake;
  note: string;
}

export type UserGuildSettingsEvent = UserGuildSettings;
export interface InteractionEvent {
  id: Snowflake;
  nonce?: Snowflake;
}

export type InteractionModalCreateEvent = Modal;
export interface CallCreateEvent {
  channel_id: Snowflake;
  message_id: Snowflake;
  embedded_activities: Record<string, unknown>[];
  region: string;
  ringing: Snowflake[];
  voice_states: VoiceState[];
  unavailable?: boolean;
}

export interface CallUpdateEvent {
  channel_id: Snowflake;
  guild_id: Snowflake | null;
  message_id: Snowflake;
  region: string;
  ringing: Snowflake[];
}

export interface CallDeleteEvent {
  channel_id: Snowflake;
  unavailable?: boolean;
}

export interface BaseGuildSubscribePayload {
  typing: boolean;
  threads: boolean;
  activities: boolean;
  member_updates: boolean;
  members: Snowflake[];
  channels: Record<Snowflake, [number, number][]>;
  thread_member_lists: Snowflake[];
}

export interface GuildSubscribePayload extends BaseGuildSubscribePayload {
  guild_id: Snowflake;
}

export type BulkGuildSubscribePayload = Record<Snowflake, BaseGuildSubscribePayload>;
export interface _GuildMemberListGroup {
  id: Snowflake | 'online' | 'offline';
}

export interface GuildMemberListGroup extends _GuildMemberListGroup {
  count: number;
}

export interface _GuildMemberListGroupItem {
  group: _GuildMemberListGroup;
}

export interface _GuildMemberListMemberItem {
  member: MemberWithPresence;
}

export type GuildMemberListItem = _GuildMemberListGroupItem | _GuildMemberListMemberItem;
export interface GuildMemberListSyncOP {
  op: 'SYNC';
  range: [number, number];
  items: GuildMemberListItem[];
}

export interface GuildMemberListUpdateOP {
  op: 'UPDATE';
  index: number;
  item: _GuildMemberListMemberItem;
}

export interface GuildMemberListInsertOP {
  op: 'INSERT';
  index: number;
  item: _GuildMemberListMemberItem;
}

export interface GuildMemberListDeleteOP {
  op: 'DELETE';
  index: number;
}

export interface GuildMemberListInvalidateOP {
  op: 'INVALIDATE';
  range: [number, number];
}

export interface GuildMemberListUpdateEvent {
  id: Snowflake | 'everyone';
  guild_id: Snowflake;
  member_count: number;
  online_count: number;
  groups: GuildMemberListGroup[];
  ops: GuildMemberListOP[];
}
