// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { GuildScheduledEvent } from './scheduled_event';
import type { GuildSticker } from './sticker';
import type { Snowflake } from './snowflake';
import type { GuildChannel, StageInstance } from './channel';
import type { VoiceState } from './voice';
import type { WelcomeScreen } from './welcome_screen';
import type { PartialPresenceUpdate } from './activity';
import type { Role } from './role';
import type { MemberWithUser } from './member';
import type { Emoji } from './emoji';
import type { User } from './user';
import type { Thread } from './threads';

export interface Ban {
  reason: string | null;
  user: User;
}

export interface UnavailableGuild {
  id: Snowflake;
  unavailable?: boolean;
}

export type DefaultMessageNotificationLevel = 0 | 1;
export type ExplicitContentFilterLevel = 0 | 1 | 2;
export type MFALevel = 0 | 1;
export type VerificationLevel = 0 | 1 | 2 | 3 | 4;
export type NSFWLevel = 0 | 1 | 2 | 3;
export type PremiumTier = 0 | 1 | 2 | 3;
export type ApplicationCommandCounts = Record<1 | 2 | 3, number>;
export interface BaseGuild {
  id: Snowflake;
  name: string;
  icon: string | null;
  features: string[];
}

export interface PartialGuild extends BaseGuild {
  description: string | null;
  splash: string | null;
  discovery_splash: string | null;
  home_header: string | null;
}

export interface _GuildMedia extends PartialGuild {
  emojis: Emoji[];
  stickers: GuildSticker[];
}

export interface _GuildCounts {
  approximate_member_count: number;
  approximate_presence_count: number;
}

export interface GuildPreview extends _GuildMedia, _GuildCounts {
}

export interface Guild extends UnavailableGuild, _GuildMedia {
  owner_id: Snowflake;
  region: string;
  afk_channel_id: Snowflake | null;
  afk_timeout: number;
  verification_level: VerificationLevel;
  default_message_notifications: DefaultMessageNotificationLevel;
  explicit_content_filter: ExplicitContentFilterLevel;
  roles: Role[];
  mfa_level: MFALevel;
  nsfw_level: NSFWLevel;
  application_id: Snowflake | null;
  system_channel_id: Snowflake | null;
  system_channel_flags: number;
  rules_channel_id: Snowflake | null;
  vanity_url_code: string | null;
  banner: string | null;
  premium_tier: PremiumTier;
  preferred_locale: string;
  public_updates_channel_id: Snowflake | null;
  stickers: GuildSticker[];
  stage_instances: StageInstance[];
  guild_scheduled_events: GuildScheduledEvent[];
  owner?: boolean;
  permissions?: string;
  widget_enabled?: boolean;
  widget_channel_id?: Snowflake | null;
  joined_at?: string | null;
  large?: boolean;
  member_count?: number;
  voice_states?: VoiceState[];
  members?: MemberWithUser[];
  channels?: GuildChannel[];
  presences?: PartialPresenceUpdate[];
  threads?: Thread[];
  max_presences?: number | null;
  max_members?: number;
  premium_subscription_count?: number;
  max_video_channel_users?: number;
  hub_type: 0 | 1 | 2 | null;
}

export interface UserGuild extends BaseGuild {
  owner: boolean;
  permissions: string;
  approximate_member_count?: number;
  approximate_presence_count?: number;
}

export interface InviteGuild {
  id: Snowflake;
  name: string;
  icon: string | null;
  description: string | null;
  banner: string | null;
  splash: string | null;
  verification_level: VerificationLevel;
  features: string[];
  vanity_url_code: string | null;
  premium_subscription_count?: number;
  nsfw: boolean;
  nsfw_level: NSFWLevel;
  welcome_screen?: WelcomeScreen;
}

export interface GuildWithCounts extends Guild, _GuildCounts {
}

export interface GuildPrune {
  pruned: number | null;
}

export interface GuildMFALevel {
  level: MFALevel;
}

export interface ChannelPositionUpdate {
  id: Snowflake;
  position: number | null;
  lock_permissions: boolean | null;
  parent_id: Snowflake | null;
}

export interface _RolePositionRequired {
  id: Snowflake;
}

export interface RolePositionUpdate extends _RolePositionRequired {
  position: Snowflake | null;
}

export interface AdminServerEligibility {
  eligible_for_admin_server: boolean;
}

export interface CommandScopeMigration {
  integration_ids_with_app_commands: Snowflake[];
}

export interface SupplementalGuild extends UnavailableGuild {
  embedded_activities: list;
  voice_states: VoiceState[];
}
