// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { Guild } from './guild';
import type { Snowflake } from './snowflake';

export interface HubWaitlist {
  email: string;
  email_domain: string;
  school: string;
  user_id: Snowflake;
}

export interface HubGuild {
  id: Snowflake;
  name: string;
  icon: string | null;
}

export interface EmailDomainLookup {
  guilds_info?: HubGuild[];
  has_matching_guild: boolean;
}

export interface EmailDomainVerification {
  guild: Guild;
  joined: boolean;
}
