// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { IntegrationApplication } from './application';
import type { ApplicationCommand } from './command';
import type { ModalActionRow } from './components';
import type { Member } from './member';
import type { PartialAttachment } from './message';
import type { Snowflake } from './snowflake';
import type { User } from './user';

export type InteractionType = 1 | 2 | 3 | 4 | 5;
export interface _BaseApplicationCommandInteractionDataOption {
  name: string;
}

export interface _CommandGroupApplicationCommandInteractionDataOption extends _BaseApplicationCommandInteractionDataOption {
  type: 1 | 2;
  options: ApplicationCommandInteractionDataOption[];
}

export interface _BaseValueApplicationCommandInteractionDataOption extends _BaseApplicationCommandInteractionDataOption {
  focused: boolean;
}

export interface _StringValueApplicationCommandInteractionDataOption extends _BaseValueApplicationCommandInteractionDataOption {
  type: 3;
  value: string;
}

export interface _IntegerValueApplicationCommandInteractionDataOption extends _BaseValueApplicationCommandInteractionDataOption {
  type: 4;
  value: number;
}

export interface _BooleanValueApplicationCommandInteractionDataOption extends _BaseValueApplicationCommandInteractionDataOption {
  type: 5;
  value: boolean;
}

export interface _SnowflakeValueApplicationCommandInteractionDataOption extends _BaseValueApplicationCommandInteractionDataOption {
  type: 6 | 7 | 8 | 9 | 11;
  value: Snowflake;
}

export interface _NumberValueApplicationCommandInteractionDataOption extends _BaseValueApplicationCommandInteractionDataOption {
  type: 10;
  value: number;
}

export interface _BaseApplicationCommandInteractionData {
  id: Snowflake;
  name: string;
  version: Snowflake;
  guild_id?: Snowflake;
  application_command: ApplicationCommand;
  attachments: PartialAttachment[];
  options: ApplicationCommandInteractionDataOption[];
}

export interface ChatInputCommandInteractionData extends _BaseApplicationCommandInteractionData {
  type: 1;
}

export interface _BaseNonChatInputApplicationCommandInteractionData extends _BaseApplicationCommandInteractionData {
  target_id: Snowflake;
}

export interface UserCommandInteractionData extends _BaseNonChatInputApplicationCommandInteractionData {
  type: 2;
}

export interface MessageCommandInteractionData extends _BaseNonChatInputApplicationCommandInteractionData {
  type: 3;
}

export interface _BaseMessageComponentInteractionData {
  custom_id: string;
}

export interface ButtonInteractionData extends _BaseMessageComponentInteractionData {
  component_type: 2;
}

export interface SelectInteractionData extends _BaseMessageComponentInteractionData {
  component_type: 3;
  values: string[];
}

export type MessageComponentInteractionData = ButtonInteractionData | SelectInteractionData;
export interface TextInputInteractionData {
  type: 4;
  custom_id: string;
  value: string;
}

export type ModalSubmitComponentInteractionData = TextInputInteractionData;
export interface MessageActionRowData {
  type: 1;
  components: MessageComponentInteractionData[];
}

export interface ModalSubmitActionRowData {
  type: 1;
  components: ModalSubmitComponentInteractionData[];
}

export interface ModalSubmitInteractionData {
  id: Snowflake;
  custom_id: string;
  components: ModalSubmitComponentInteractionData[];
}

export type ActionRowInteractionData = MessageActionRowData | ModalSubmitActionRowData;
export type ComponentInteractionData = MessageComponentInteractionData | ModalSubmitComponentInteractionData;
export interface MessageInteraction {
  id: Snowflake;
  type: InteractionType;
  name: string;
  user: User;
  member?: Member;
}

export interface Modal {
  id: number;
  nonce?: Snowflake;
  channel_id: Snowflake;
  title: string;
  custom_id: string;
  application: IntegrationApplication;
  components: ModalActionRow[];
}
