// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { IntegrationApplication, RoleConnectionMetadata } from './application';
import type { Guild } from './guild';
import type { Snowflake } from './snowflake';
import type { APIUser } from './user';

export interface IntegrationAccount {
  id: string;
  name: string;
}

export type IntegrationExpireBehavior = 0 | 1;
export interface PartialIntegration {
  id: Snowflake;
  name: string;
  type: IntegrationType;
  account: IntegrationAccount;
  application_id?: Snowflake;
}

export type IntegrationType = 'twitch' | 'youtube' | 'discord' | 'guild_subscription';
export interface BaseIntegration extends PartialIntegration {
  enabled: boolean;
  user?: APIUser;
}

export interface StreamIntegration extends BaseIntegration {
  role_id: Snowflake | null;
  enable_emoticons: boolean;
  subscriber_count: number;
  revoked: boolean;
  expire_behavior: IntegrationExpireBehavior;
  expire_grace_period: number;
  syncing: boolean;
  synced_at: string;
}

export interface BotIntegration extends BaseIntegration {
  application: IntegrationApplication;
  scopes: string[];
  role_connections_metadata?: RoleConnectionMetadata[];
}

export interface ConnectionIntegration extends BaseIntegration {
  guild: Guild;
}

export type Integration = BaseIntegration | StreamIntegration | BotIntegration | ConnectionIntegration;
