// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { PartialApplication } from './application';
import type { InviteStageInstance, PartialChannel } from './channel';
import type { InviteCreateEvent, InviteDeleteEvent } from './gateway';
import type { InviteGuild, _GuildCounts } from './guild';
import type { GuildScheduledEvent } from './scheduled_event';
import type { Snowflake } from './snowflake';
import type { PartialUser } from './user';

export type InviteTargetType = 1 | 2;
export interface _InviteMetadata {
  uses?: number;
  max_uses?: number;
  max_age?: number;
  temporary?: boolean;
  created_at: string;
}

export interface _InviteTargetType {
  target_type: InviteTargetType;
  target_user: PartialUser;
  target_application: PartialApplication;
}

export interface VanityInvite {
  code: string | null;
  uses: number;
}

export interface PartialInvite extends _InviteTargetType {
  code: string;
  type: 0 | 1 | 2;
  channel: PartialChannel | null;
  guild_id?: Snowflake;
  guild?: InviteGuild;
  inviter?: PartialUser;
  flags?: number;
  expires_at: string | null;
  guild_scheduled_event?: GuildScheduledEvent;
  stage_instance?: InviteStageInstance;
}

export interface InviteWithCounts extends PartialInvite, _GuildCounts {
}

export interface InviteWithMetadata extends PartialInvite, _InviteMetadata {
}

export interface AcceptedInvite extends InviteWithCounts {
  new_member: boolean;
  show_verification_form: boolean;
}

export type Invite = PartialInvite | InviteWithCounts | InviteWithMetadata | AcceptedInvite;
export type GatewayInvite = InviteCreateEvent | InviteDeleteEvent;
