// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { Branch, PartialApplication } from './application';
import type { Entitlement } from './entitlements';
import type { Snowflake } from './snowflake';
import type { PartialSKU } from './store';

export interface LibraryApplication {
  created_at: string;
  application: PartialApplication;
  sku_id: Snowflake;
  sku: PartialSKU;
  entitlements: Entitlement[];
  flags: number;
  branch_id: Snowflake;
  branch?: Branch;
}
