// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { BasePresenceUpdate } from './activity';
import type { SnowflakeList } from './snowflake';
import type { PartialUser } from './user';

export interface Nickname {
  nick: string;
}

export interface PartialMember {
  roles: SnowflakeList;
  joined_at: string;
  deaf: boolean;
  mute: boolean;
  flags: number;
}

export interface Member extends PartialMember {
  avatar: string | null;
  user: PartialUser;
  nick: string;
  premium_since: string | null;
  pending: boolean;
  communication_disabled_until: string;
}

export interface _OptionalMemberWithUser extends PartialMember {
  avatar: string | null;
  nick: string;
  premium_since: string | null;
  pending: boolean;
  communication_disabled_until: string;
}

export interface MemberWithUser extends _OptionalMemberWithUser {
  user: PartialUser;
}

export interface MemberWithPresence extends MemberWithUser {
  presence: BasePresenceUpdate;
}

export interface PrivateMember extends MemberWithUser {
  bio: string;
  banner: string | null;
}

export interface UserWithMember extends PartialUser {
  member: _OptionalMemberWithUser;
}
