// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { Snowflake, SnowflakeList } from './snowflake';
import type { Member, UserWithMember } from './member';
import type { User } from './user';
import type { PartialEmoji } from './emoji';
import type { Embed } from './embed';
import type { ChannelType } from './channel';
import type { MessageActionRow } from './components';
import type { MessageInteraction } from './interactions';
import type { BaseApplication } from './application';
import type { StickerItem } from './sticker';
import type { Thread, ThreadMember } from './threads';

export interface PartialMessage {
  channel_id: Snowflake;
  guild_id?: Snowflake;
}

export interface ChannelMention {
  id: Snowflake;
  guild_id: Snowflake;
  type: ChannelType;
  name: string;
}

export interface Reaction {
  count: number;
  me: boolean;
  emoji: PartialEmoji;
}

export interface Attachment {
  id: Snowflake;
  filename: string;
  size: number;
  url: string;
  proxy_url: string;
  height?: number | null;
  width?: number | null;
  description?: string;
  content_type?: string;
  spoiler?: boolean;
  ephemeral?: boolean;
  duration_secs?: number;
  waveform?: string;
  flags?: number;
}

export type MessageActivityType = 1 | 2 | 3 | 5;
export interface MessageActivity {
  type: MessageActivityType;
  party_id: string;
}

export interface MessageReference {
  message_id: Snowflake;
  channel_id: Snowflake;
  guild_id: Snowflake;
  fail_if_not_exists: boolean;
}

export interface Call {
  participants: Snowflake[];
  ended_timestamp: string | null;
}

export interface RoleSubscriptionData {
  role_subscription_listing_id: Snowflake;
  tier_name: string;
  total_months_subscribed: number;
  is_renewal: boolean;
}

export type MessageType = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 14 | 15 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 | 31 | 32;
export interface Message extends PartialMessage {
  id: Snowflake;
  author: User;
  content: string;
  timestamp: string;
  edited_timestamp: string | null;
  tts: boolean;
  mention_everyone: boolean;
  mentions: UserWithMember[];
  mention_roles: SnowflakeList;
  attachments: Attachment[];
  embeds: Embed[];
  pinned: boolean;
  type: MessageType;
  member?: Member;
  mention_channels?: ChannelMention[];
  reactions?: Reaction[];
  nonce?: number | string;
  webhook_id?: Snowflake;
  activity?: MessageActivity;
  application?: BaseApplication;
  application_id?: Snowflake;
  message_reference?: MessageReference;
  flags?: number;
  sticker_items?: StickerItem[];
  referenced_message?: Message | null;
  interaction?: MessageInteraction;
  components?: MessageActionRow[];
  position?: number;
  call?: Call;
  role_subscription_data?: RoleSubscriptionData;
  hit?: boolean;
  thread?: Thread;
}

export type AllowedMentionType = 'roles' | 'users' | 'everyone';
export interface AllowedMentions {
  parse: AllowedMentionType[];
  roles: SnowflakeList;
  users: SnowflakeList;
  replied_user: boolean;
}

export interface MessageSearchIndexingResult {
  message: string;
  code: number;
  documents_indexed: number;
  retry_after: number;
}

export interface MessageSearchResult {
  messages: Message[][];
  threads?: Thread[];
  members?: ThreadMember[];
  total_results: number;
  analytics_id: string;
  doing_deep_historical_index?: boolean;
}

export type MessageSearchAuthorType = 'user' | '-user' | 'bot' | '-bot' | 'webhook' | '-webhook';
export type MessageSearchHasType = 'image' | '-image' | 'sound' | '-sound' | 'video' | '-video' | 'file' | '-file' | 'sticker' | '-sticker' | 'embed' | '-embed' | 'link' | '-link';
export type MessageSearchSortType = 'timestamp' | 'relevance';
export type MessageSearchSortOrder = 'desc' | 'asc';
export interface PartialAttachment {
  id?: Snowflake;
  filename: string;
  description?: string;
  uploaded_filename?: string;
}

export interface UploadedAttachment {
  id?: Snowflake;
  filename: string;
  file_size: number;
}

export interface CloudAttachment {
  id?: Snowflake;
  upload_url: string;
  upload_filename: string;
}

export interface CloudAttachments {
  attachments: CloudAttachment[];
}
