// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { PartialApplication } from './application';
import type { Snowflake } from './snowflake';
import type { PartialUser } from './user';

export interface OAuth2Token {
  id: Snowflake;
  application: PartialApplication;
  scopes: string[];
}

export interface BotUser extends PartialUser {
  approximate_guild_count: number;
}

export interface OAuth2Guild {
  id: Snowflake;
  name: string;
  icon: string | null;
  permissions: string;
  mfa_level: number;
}

export interface OAuth2Authorization {
  authorized: boolean;
  user: PartialUser;
  application: PartialApplication;
  bot?: BotUser;
  guilds?: OAuth2Guild[];
  redirect_uri?: string | null;
}

export interface OAuth2Location {
  location: string;
}

export interface WebhookChannel {
  id: Snowflake;
  name: string;
}
