// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { PartialPaymentSource } from './billing';
import type { Snowflake } from './snowflake';
import type { PublicSKU } from './store';
import type { PartialSubscription } from './subscriptions';

export interface PartialPayment {
  id: Snowflake;
  amount: number;
  tax: number;
  tax_inclusive: boolean;
  currency: string;
}

export interface Payment extends PartialPayment {
  amount_refunded: number;
  description: string;
  status: 0 | 1 | 2 | 3 | 4 | 5;
  created_at: string;
  sku_id?: Snowflake;
  sku_price?: number;
  sku_subscription_plan_id?: Snowflake;
  payment_gateway?: 1 | 2 | 3 | 4 | 5 | 6;
  payment_gateway_payment_id?: string;
  downloadable_invoice?: string;
  downloadable_refund_invoices?: string[];
  refund_disqualification_reasons?: string[];
  flags: number;
  sku?: PublicSKU;
  payment_source?: PartialPaymentSource;
  subscription?: PartialSubscription;
}
