// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { ApplicationInstallParams, RoleConnection } from './application';
import type { Emoji } from './emoji';
import type { PrivateMember as ProfileMember } from './member';
import type { Snowflake } from './snowflake';
import type { APIUser, PartialConnection, PremiumType } from './user';

export interface ProfileUser extends APIUser {
  bio: string;
}

export interface ProfileEffect {
  id: Snowflake;
}

export interface ProfileMetadata {
  guild_id: number;
  bio: string;
  banner: string | null;
  accent_color: number | null;
  theme_colors: [number, number] | null;
  emoji: Emoji | null;
  popout_animation_particle_type: Snowflake | null;
  profile_effect: ProfileEffect | null;
  pronouns: string;
}

export interface MutualGuild {
  id: Snowflake;
  nick: string | null;
}

export interface ProfileApplication {
  id: Snowflake;
  verified: boolean;
  popular_application_command_ids?: Snowflake[];
  primary_sku_id?: Snowflake;
  flags: number;
  custom_install_url?: string;
  install_params?: ApplicationInstallParams;
}

export interface ProfileBadge {
  id: string;
  description: string;
  icon: string;
  link?: string;
}

export interface Profile {
  user: ProfileUser;
  user_profile: ProfileMetadata | null;
  badges: ProfileBadge[];
  guild_member?: ProfileMember;
  guild_member_profile?: ProfileMetadata | null;
  guild_badges: ProfileBadge[];
  mutual_guilds?: MutualGuild[];
  mutual_friends_count?: number;
  connected_accounts: PartialConnection[];
  application_role_connections?: RoleConnection[];
  premium_type: PremiumType | null;
  premium_since: string | null;
  premium_guild_since: string | null;
  legacy_username: string | null;
  application?: ProfileApplication;
}
