// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { Snowflake } from './snowflake';
import type { SubscriptionTrial } from './subscriptions';

export interface Promotion {
  id: Snowflake;
  trial_id?: Snowflake;
  start_date: string;
  end_date: string;
  flags: number;
  outbound_title: string;
  outbound_redemption_modal_body: string;
  outbound_redemption_page_link?: string;
  outbound_redemption_url_format?: string;
  outbound_restricted_countries?: string[];
  outbound_terms_and_conditions: string;
  inbound_title?: string;
  inbound_body_text?: string;
  inbound_help_center_link?: string;
  inbound_restricted_countries?: string[];
}

export interface ClaimedPromotion {
  promotion: Promotion;
  code: string;
  claimed_at: string;
}

export interface TrialOffer {
  id: Snowflake;
  expires_at: string | null;
  trial_id: Snowflake;
  subscription_trial: SubscriptionTrial;
}

export interface PromotionalPrice {
  amount: number;
  currency: string;
}

export interface PricingPromotion {
  plan_id: Snowflake;
  country_code: string;
  payment_source_types: string[];
  price: PromotionalPrice;
}

export interface WrappedPricingPromotion {
  country_code: string;
  localized_pricing_promo: PricingPromotion | null;
}
