// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { Snowflake } from './snowflake';

export type ReadStateType = 0 | 1 | 2 | 3 | 4;
export interface ReadState {
  id: Snowflake;
  read_state_type?: ReadStateType;
  last_message_id?: Snowflake;
  last_acked_id?: Snowflake;
  last_pin_timestamp?: string;
  mention_count?: number;
  badge_count?: number;
  flags?: number;
  last_viewed?: number | null;
}

export interface BulkReadState {
  channel_id: Snowflake;
  message_id: Snowflake;
  read_state_type: ReadStateType;
}

export interface AcknowledgementToken {
  token: string | null;
}
