// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { Snowflake } from './snowflake';

export interface Role {
  id: Snowflake;
  name: string;
  color: number;
  hoist: boolean;
  position: number;
  permissions: string;
  managed: boolean;
  mentionable: boolean;
  icon?: string | null;
  unicode_emoji?: string | null;
  tags?: RoleTags;
}

export interface RoleTags {
  bot_id: Snowflake;
  integration_id: Snowflake;
  subscription_listing_id: Snowflake;
  premium_subscriber: null;
  available_for_purchase: null;
  guild_connections: null;
}
