// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { Snowflake } from './snowflake';
import type { User } from './user';
import type { Member } from './member';
import type { PrivacyLevel as PrivacyLevel } from './channel';

export type EventStatus = 1 | 2 | 3 | 4;
export type EntityType = 1 | 2 | 3;
export interface _BaseGuildScheduledEvent {
  id: Snowflake;
  guild_id: Snowflake;
  entity_id: Snowflake | null;
  name: string;
  scheduled_start_time: string;
  privacy_level: PrivacyLevel;
  status: EventStatus;
  creator_id?: Snowflake | null;
  description?: string | null;
  creator?: User;
  user_count?: number;
  image?: string | null;
  sku_ids: Snowflake[];
}

export interface _VoiceChannelScheduledEvent extends _BaseGuildScheduledEvent {
  channel_id: Snowflake;
  entity_metadata: None;
  scheduled_end_time?: string | null;
}

export interface StageInstanceScheduledEvent extends _VoiceChannelScheduledEvent {
  entity_type: 1;
}

export interface VoiceScheduledEvent extends _VoiceChannelScheduledEvent {
  entity_type: 2;
}

export interface EntityMetadata {
  location: string;
}

export interface ExternalScheduledEvent extends _BaseGuildScheduledEvent {
  channel_id: None;
  entity_metadata: EntityMetadata;
  scheduled_end_time: string;
  entity_type: 3;
}

export type GuildScheduledEvent = StageInstanceScheduledEvent | VoiceScheduledEvent | ExternalScheduledEvent;
export interface _WithUserCount {
  user_count: number;
}

export interface _StageInstanceScheduledEventWithUserCount extends StageInstanceScheduledEvent, _WithUserCount {
}

export interface _VoiceScheduledEventWithUserCount extends VoiceScheduledEvent, _WithUserCount {
}

export interface _ExternalScheduledEventWithUserCount extends ExternalScheduledEvent, _WithUserCount {
}

export interface UserWithMember extends User {
  guild_member: Member;
}

export interface ScheduledEventUsers {
  users: User[];
}

export interface ScheduledEventUsersWithMember {
  users: UserWithMember[];
}

export interface SubscribedGuildScheduledEvent {
  guild_scheduled_event_id: Snowflake;
  user_id: Snowflake;
}
