// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { Snowflake } from './snowflake';
import type { User } from './user';

export type StickerFormatType = 1 | 2 | 3 | 4;
export interface StickerItem {
  id: Snowflake;
  name: string;
  format_type: StickerFormatType;
}

export interface BaseSticker {
  id: Snowflake;
  name: string;
  description: string;
  tags: string;
  format_type: StickerFormatType;
}

export interface StandardSticker extends BaseSticker {
  type: 1;
  sort_value: number;
  pack_id: Snowflake;
}

export interface GuildSticker extends BaseSticker {
  type: 2;
  available?: boolean;
  guild_id: Snowflake;
  user?: User;
}

export type Sticker = StandardSticker | GuildSticker;
export interface StickerPack {
  id: Snowflake;
  stickers: StandardSticker[];
  name: string;
  sku_id: Snowflake;
  cover_sticker_id: Snowflake | null;
  description: string;
  banner_asset_id: Snowflake | null;
}

export interface CreateGuildSticker {
  name: string;
  tags: string;
  description?: string;
}

export interface ListPremiumStickerPacks {
  sticker_packs: StickerPack[];
}
