// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { PartialApplication, StoreAsset } from './application';
import type { Entitlement } from './entitlements';
import type { PartialGuild } from './guild';
import type { LibraryApplication } from './library';
import type { Snowflake } from './snowflake';
import type { PartialUser } from './user';

export type LOCALIZED_STR = string | Record<string, string>;
export interface StoreNote {
  content: string;
  user: PartialUser | null;
}

export interface SystemRequirement {
  ram: number;
  disk: number;
  operating_system_version: LOCALIZED_STR;
  cpu: LOCALIZED_STR;
  gpu: LOCALIZED_STR;
  sound_card: LOCALIZED_STR;
  directx: LOCALIZED_STR;
  network: LOCALIZED_STR;
  notes: LOCALIZED_STR;
}

export interface SystemRequirements {
  minimum: SystemRequirement;
  recommended: SystemRequirement;
}

export interface CarouselItem {
  asset_id: Snowflake;
  youtube_video_id: string;
}

export interface BaseStoreListing {
  id: Snowflake;
  summary?: LOCALIZED_STR;
  description?: LOCALIZED_STR;
  tagline?: LOCALIZED_STR;
  flavor_text?: string;
  entitlement_branch_id?: Snowflake;
  staff_notes?: StoreNote;
  assets?: StoreAsset[];
  carousel_items?: CarouselItem[];
  preview_video?: StoreAsset;
  header_background?: StoreAsset;
  hero_background?: StoreAsset;
  hero_video?: StoreAsset;
  box_art?: StoreAsset;
  thumbnail?: StoreAsset;
  header_logo_light_theme?: StoreAsset;
  header_logo_dark_theme?: StoreAsset;
  sku: PublicSKU;
  child_skus?: PublicSKU[];
  alternative_skus?: PublicSKU[];
  published_at?: string;
  unpublished_at?: string;
}

export interface PublicStoreListing extends BaseStoreListing {
  guild?: PartialGuild;
}

export interface PrivateStoreListing extends BaseStoreListing {
  published: boolean;
}

export type StoreListing = PublicStoreListing | PrivateStoreListing;
export interface PremiumPrice {
  amount: number;
  percentage: number;
}

export interface SKUPrice {
  currency: string;
  currency_exponent: number;
  amount: number;
  sale_amount?: number | null;
  sale_percentage?: number;
  premium?: Record<1 | 2 | 3, PremiumPrice>;
}

export interface ContentRating {
  rating: number;
  descriptors: number[];
}

export type SKUType = 1 | 2 | 3 | 4 | 5 | 6;
export interface PartialSKU {
  id: Snowflake;
  type: SKUType;
  premium: boolean;
  preorder_release_date: string | null;
  preorder_released_at: string | null;
}

export interface BaseSKU extends PartialSKU {
  id: Snowflake;
  type: SKUType;
  product_line: 1 | 2 | 3 | 4 | 5 | 6 | 7 | null;
  name: LOCALIZED_STR;
  summary?: LOCALIZED_STR;
  legal_notice?: LOCALIZED_STR;
  slug: string;
  dependent_sku_id: Snowflake | null;
  application_id: Snowflake;
  application?: PartialApplication;
  flags: number;
  access_level: 1 | 2 | 3;
  features: number[];
  locales?: string[];
  genres?: number[];
  available_regions?: string[];
  system_requirements?: Record<1 | 2 | 3, SystemRequirements>;
  release_date: string | null;
  preorder_release_date?: string | null;
  preorder_released_at?: string | null;
  external_purchase_url?: string;
  premium?: boolean;
  restricted?: boolean;
  exclusive?: boolean;
  deleted?: boolean;
  show_age_gate: boolean;
  manifest_labels: Snowflake[] | null;
}

export interface PublicSKU extends BaseSKU {
  bundled_skus?: PublicSKU[];
  price: SKUPrice;
  content_rating_agency?: 1 | 2;
  content_rating?: ContentRating;
}

export interface PrivateSKU extends BaseSKU {
  bundled_skus?: PrivateSKU[];
  price_tier: number;
  price: Record<string, number>;
  sale_price_tier: number;
  sale_price: Record<string, number>;
  content_ratings: Record<1 | 2, ContentRating>;
}

export type SKU = PublicSKU | PrivateSKU;
export interface SKUPurchase {
  entitlements: Entitlement[];
  library_applications?: LibraryApplication[];
  gift_code?: string;
}
