// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { Snowflake } from './snowflake';
import type { PartialUser } from './user';

export interface PremiumGuildSubscription {
  id: Snowflake;
  guild_id: Snowflake;
  user_id: Snowflake;
  user?: PartialUser;
  ended: boolean;
  ends_at?: string;
}

export interface PremiumGuildSubscriptionSlot {
  id: Snowflake;
  subscription_id: Snowflake;
  canceled: boolean;
  cooldown_ends_at: string | null;
  premium_guild_subscription: PremiumGuildSubscription | null;
}

export interface PremiumGuildSubscriptionCooldown {
  ends_at: string;
  limit: number;
  remaining: number;
}

export interface SubscriptionItem {
  id: Snowflake;
  quantity: number;
  plan_id: Snowflake;
}

export interface SubscriptionDiscount {
  type: 1 | 2 | 3 | 4;
  amount: number;
}

export interface SubscriptionInvoiceItem {
  id: Snowflake;
  quantity: number;
  amount: number;
  proration: boolean;
  subscription_plan_id: Snowflake;
  subscription_plan_price: number;
  discounts: SubscriptionDiscount[];
  tenant_metadata?: Record<string, any>;
}

export interface SubscriptionInvoice {
  id: Snowflake;
  status?: 1 | 2 | 3 | 4;
  currency: string;
  subtotal: number;
  tax: number;
  total: number;
  tax_inclusive: boolean;
  items: SubscriptionInvoiceItem[];
  current_period_start: string;
  current_period_end: string;
  applied_discount_ids?: Snowflake[];
  applied_user_discounts?: Record<Snowflake, any | null>;
}

export interface SubscriptionRenewalMutations {
  payment_gateway_plan_id: string | null;
  items: SubscriptionItem[];
}

export interface PartialSubscription {
  id: Snowflake;
  type: 1 | 2 | 3;
  payment_gateway: 1 | 2 | 3 | 4 | 5 | 6 | null;
  currency: string;
  items: SubscriptionItem[];
  payment_gateway_plan_id: string | null;
  payment_gateway_subscription_id?: string | null;
  current_period_start: string;
  current_period_end: string;
  streak_started_at?: string;
}

export interface Subscription extends PartialSubscription {
  status: 0 | 1 | 2 | 3 | 4 | 5 | 6;
  renewal_mutations?: SubscriptionRenewalMutations;
  trial_id?: Snowflake;
  payment_source_id: Snowflake | null;
  created_at: string;
  canceled_at?: string;
  country_code: string | null;
  trial_ends_at?: string;
  metadata?: Record<string, any>;
  latest_invoice?: SubscriptionInvoice;
  use_storekit_resubscribe: boolean;
  price: number | null;
}

export interface SubscriptionTrial {
  id: Snowflake;
  interval: 1 | 2 | 3;
  interval_count: number;
  sku_id: Snowflake;
}

export interface SubscriptionPrice {
  currency: string;
  amount: number;
  exponent: number;
}

export interface CountryCode {
  country_code: string;
}

export interface SubscriptionCountryPrice extends CountryCode {
  prices: SubscriptionPrice[];
}

export interface SubscriptionPrices {
  country_prices: SubscriptionCountryPrice;
  payment_source_prices: Record<Snowflake, SubscriptionPrice[]>;
}

export interface PartialSubscriptionPlan {
  id: Snowflake;
  name: string;
  sku_id: Snowflake;
  interval: 1 | 2 | 3;
  interval_count: number;
  tax_inclusive: boolean;
}

export interface SubscriptionPlan extends PartialSubscriptionPlan {
  prices: Record<0 | 1 | 2 | 3 | 4, SubscriptionPrices>;
  price_tier: None;
  currency: string;
  price: number;
  discount_price?: number;
  fallback_currency?: string;
  fallback_price?: number;
  fallback_discount_price?: number;
}
