// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { PartialUser } from './user';
import type { Snowflake } from './snowflake';

export interface TeamMember {
  user: PartialUser;
  membership_state: number;
  permissions: string[];
  team_id: Snowflake;
}

export interface Team {
  id: Snowflake;
  name: string;
  owner_user_id: Snowflake;
  icon: string | null;
  payout_account_status?: 1 | 2 | 3 | 4 | 5 | 6 | null;
  stripe_connect_account_id?: string | null;
  members?: TeamMember[];
}

export interface TeamPayout {
  id: Snowflake;
  user_id: Snowflake;
  amount: number;
  status: 1 | 2 | 3 | 4 | 5;
  period_start: string;
  period_end: string | null;
  payout_date: string | null;
  latest_tipalti_submission_response?: dict;
}
