// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { Snowflake } from './snowflake';
import type { User } from './user';
import type { Guild } from './guild';

export interface CreateTemplate {
  name: string;
  icon: bytes | null;
}

export interface Template {
  code: string;
  name: string;
  description: string | null;
  usage_count: number;
  creator_id: Snowflake;
  creator: User;
  created_at: string;
  updated_at: string;
  source_guild_id: Snowflake;
  serialized_source_guild: Guild;
  is_dirty: boolean | null;
}
