// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { BasePresenceUpdate } from './activity';
import type { MemberWithUser } from './member';
import type { Message } from './message';
import type { Snowflake } from './snowflake';

export type ThreadType = 10 | 11 | 12;
export type ThreadArchiveDuration = 60 | 1440 | 4320 | 10080;
export interface BaseThreadMember {
  user_id: Snowflake;
  member: MemberWithUser;
  presence: BasePresenceUpdate;
}

export interface ThreadMember {
  id: Snowflake;
  user_id: Snowflake;
  join_timestamp: string;
  flags: number;
  member?: MemberWithUser;
  presence?: BasePresenceUpdate;
}

export interface ThreadMetadata {
  archived: boolean;
  auto_archive_duration: ThreadArchiveDuration;
  archive_timestamp: string;
  archiver_id?: Snowflake;
  locked?: boolean;
  invitable?: boolean;
  create_timestamp?: string;
}

export interface Thread {
  id: Snowflake;
  guild_id: Snowflake;
  parent_id: Snowflake;
  owner_id: Snowflake;
  name: string;
  type: ThreadType;
  member_count: number;
  message_count: number;
  rate_limit_per_user: number;
  thread_metadata: ThreadMetadata;
  member_ids_preview: Snowflake[];
  member?: ThreadMember;
  last_message_id?: Snowflake | null;
  last_pin_timestamp?: string | null;
  newly_created?: boolean;
  flags?: number;
  applied_tags?: Snowflake[];
}

export interface ThreadPaginationPayload {
  threads: Thread[];
  members: ThreadMember[];
  has_more: boolean;
}

export interface ForumThread extends Thread {
  message: Message;
}
