// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { ConnectionIntegration } from './integration';
import type { Snowflake } from './snowflake';

export interface PartialUser {
  id: Snowflake;
  username: string;
  discriminator: string;
  avatar: string | null;
  avatar_decoration_data?: UserAvatarDecorationData | null;
  public_flags?: number;
  bot?: boolean;
  system?: boolean;
  global_name: string | null;
  premium_type?: PremiumType;
}

export type ConnectionType = 'battlenet' | 'contacts' | 'crunchyroll' | 'ebay' | 'epicgames' | 'facebook' | 'github' | 'instagram' | 'leagueoflegends' | 'paypal' | 'playstation' | 'reddit' | 'riotgames' | 'samsung' | 'spotify' | 'skype' | 'steam' | 'tiktok' | 'twitch' | 'twitter' | 'youtube' | 'xbox';
export type ConnectionVisibilty = 0 | 1;
export type PremiumType = 0 | 1 | 2 | 3;
export interface APIUser extends PartialUser {
  banner: string | null;
  accent_color: number | null;
}

export interface User extends APIUser {
  mfa_enabled: boolean;
  locale: string;
  verified: boolean;
  email: string | null;
  flags: number;
  purchased_flags: number;
  premium_usage_flags: number;
  premium_type: PremiumType;
  bio: string;
  analytics_token: string;
  phone: string | null;
  token: string;
  nsfw_allowed: boolean | null;
}

export interface UserAvatarDecorationData {
  asset: string;
  sku_id?: Snowflake;
}

export interface PomeloAttempt {
  taken: boolean;
}

export interface PomeloSuggestion {
  username: string;
}

export interface PartialConnection {
  id: string;
  type: ConnectionType;
  name: string;
  verified: boolean;
  metadata?: Record<string, any>;
}

export interface Connection extends PartialConnection {
  revoked: boolean;
  visibility: 0 | 1;
  metadata_visibility: 0 | 1;
  show_activity: boolean;
  friend_sync: boolean;
  two_way_link: boolean;
  integrations?: ConnectionIntegration[];
  access_token?: string;
}

export interface ConnectionAccessToken {
  access_token: string;
}

export interface ConnectionAuthorization {
  url: string;
}

export type RelationshipType = -1 | 0 | 1 | 2 | 3 | 4 | 5 | 6;
export interface Relationship {
  id: Snowflake;
  type: RelationshipType;
  user: PartialUser;
  nickname: string | null;
  since?: string;
}

export type ProtoSettingsType = 1 | 2 | 3;
export interface ProtoSettings {
  settings: string;
}

export interface _ConsentSettings {
  consented: boolean;
}

export interface PartialConsentSettings {
  personalization: _ConsentSettings;
}

export interface ConsentSettings extends PartialConsentSettings {
  usage_statistics: _ConsentSettings;
}

export interface _EmailSettingsCategories {
  communication: boolean;
  social: boolean;
  recommendations_and_events: boolean;
  tips: boolean;
  updates_and_announcements: boolean;
  family_center_digest: boolean;
}

export interface EmailSettings {
  initialized: boolean;
  categories: _EmailSettingsCategories;
}

export type MessageNotificationLevel = 0 | 1 | 2 | 3;
export type HighlightLevel = 0 | 1 | 2;
export interface MuteConfig {
  end_time: string | null;
  selected_time_window: number | null;
}

export interface ChannelOverride {
  channel_id: Snowflake;
  collapsed: boolean;
  message_notifications: MessageNotificationLevel;
  muted: boolean;
  mute_config: MuteConfig | null;
}

export interface UserGuildSettings {
  guild_id: Snowflake | null;
  channel_overrides: ChannelOverride[];
  flags: number;
  message_notifications: MessageNotificationLevel;
  notify_highlights: HighlightLevel;
  hide_muted_channels: boolean;
  mobile_push: boolean;
  muted: boolean;
  mute_config: MuteConfig | null;
  mute_scheduled_events: boolean;
  suppress_everyone: boolean;
  suppress_roles: boolean;
  version: number;
}

export interface UserAffinity {
  user_id: Snowflake;
  affinity: number;
}

export interface UserAffinities {
  user_affinities: UserAffinity[];
  inverse_user_affinities: UserAffinity[];
}

export interface GuildAffinity {
  guild_id: Snowflake;
  affinity: number;
}

export interface GuildAffinities {
  guild_affinities: GuildAffinity[];
}

export interface Note {
  note: string;
  user_id: Snowflake;
  note_user_id: Snowflake;
}

export interface FriendSuggestionReason {
  name: string;
  platform_type: ConnectionType;
  type: 1;
}

export interface FriendSuggestion {
  suggested_user: PartialUser;
  reasons: FriendSuggestionReason[];
  from_suggested_user_contacts?: boolean;
}

export interface Report {
  report_id: Snowflake;
}
