// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { Snowflake } from './snowflake';
import type { MemberWithUser } from './member';

export type SupportedModes = 'xsalsa20_poly1305_lite' | 'xsalsa20_poly1305_suffix' | 'xsalsa20_poly1305';
export interface BaseVoiceState {
  user_id: Snowflake;
  session_id: string;
  deaf: boolean;
  mute: boolean;
  self_deaf: boolean;
  self_mute: boolean;
  self_video: boolean;
  suppress: boolean;
  member?: MemberWithUser;
  self_stream?: boolean;
}

export interface VoiceState extends BaseVoiceState {
  channel_id: Snowflake;
}

export interface PrivateVoiceState extends BaseVoiceState {
  channel_id: Snowflake | null;
}

export interface GuildVoiceState extends PrivateVoiceState {
  guild_id: Snowflake;
}

export interface VoiceRegion {
  id: string;
  name: string;
  vip: boolean;
  optimal: boolean;
  deprecated: boolean;
  custom: boolean;
}

export interface VoiceServerUpdate {
  token: string;
  guild_id: Snowflake;
  channel_id: Snowflake;
  endpoint: string | null;
}

export interface VoiceIdentify {
  server_id: Snowflake;
  user_id: Snowflake;
  session_id: string;
  token: string;
}

export interface VoiceReady {
  ssrc: number;
  ip: string;
  port: number;
  modes: SupportedModes[];
  heartbeat_interval: number;
}
