// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { Snowflake } from './snowflake';
import type { User } from './user';
import type { PartialChannel } from './channel';

export interface SourceGuild {
  id: number;
  name: string;
  icon: string;
}

export interface SourceChannel {
  id: number;
  name: string;
}

export type WebhookType = 1 | 2 | 3;
export interface FollowerWebhook {
  channel_id: Snowflake;
  webhook_id: Snowflake;
  source_channel?: PartialChannel;
  source_guild?: SourceGuild;
}

export interface PartialWebhook {
  id: Snowflake;
  type: WebhookType;
  guild_id?: Snowflake;
  user?: User;
  token?: string;
}

export interface _FullWebhook {
  name: string | null;
  avatar: string | null;
  channel_id: Snowflake;
  application_id: Snowflake | null;
}

export interface Webhook extends PartialWebhook, _FullWebhook {
}
