// Auto-generated from nighty/discord/types Python definitions.
// Generated by scripts/sync-nighty-types.mjs

import type { Activity } from './activity';
import type { Snowflake } from './snowflake';
import type { User } from './user';

export interface WidgetChannel {
  id: Snowflake;
  name: string;
  position: number;
}

export interface WidgetMember extends User {
  nick: string;
  game: Activity;
  status: string;
  avatar_url: string;
  deaf: boolean;
  self_deaf: boolean;
  mute: boolean;
  self_mute: boolean;
  suppress: boolean;
}

export interface Widget {
  id: Snowflake;
  name: string;
  instant_invite: string | null;
  channels: WidgetChannel[];
  members: WidgetMember[];
  presence_count: number;
}

export interface WidgetSettings {
  enabled: boolean;
  channel_id: Snowflake | null;
}

export interface EditWidgetSettings {
  enabled: boolean;
  channel_id: Snowflake | null;
}
